FROM datmo/keras-tensorflow:gpu-py35-jupyterlab

#RUN apt-get update

#RUN apt-get install python-tk

#RUN apt-get -y install libcanberra-gtk-module

RUN pip install --upgrade pip

RUN pip install seaborn

RUN pip install category_encoders
